# SPDX-FileCopyrightText: Christian Amsüss
# SPDX-License-Identifier: MIT

version: 2

build:
  # from the limited choice there is; preferred would be a Python image
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  builder: html
  configuration: ./doc/conf.py

python:
  install:
    - method: pip
      path: .
      extra_requirements:
      - docs
      # all except dtls (because DTLSSocket doesn't have wheels, and
      # readthedocs shouldn't be bothered with compiling C code, but then,
      # that module can be imported even when DTLSSocket is not available)
      #
      # also synced with .woodpecker.yml
      - oscore
      - ws
      - prettyprint
